sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BE8PpVXM/Vdtw0DvcNovzVd4+SYWLP8JzOcGHWLwrwcIasAe6b+jUN71ywQTQ3gE1V5BxP1KDElcKlMvCDGaKMWPytwOCZvwAKP5+NxhTXy00FhiiTpwia9xsW/UzC+JPzp1w3QSvCTTkq1MglaOZuTBaMNtqNyjbLk0Z85G++dChygKmT5wBc44UiIvMR1kFnw6cS5HaRYnwMsaip97mKMOpFCt5Iv8rtA7zwml7pOPhlOTYW9bAyAtivZr3R1j3yzpNOmxApOqVoYiG2Q1qbzPhchlG+JfmgLIbEQXwxn+uo4/49SaL9fRt2kVXI2SXkdihVyIk85XkyazIuTRAJ25O6F1qx7PvqxA9t3ER6XTo5jg4igNN7vnjnsd9ATo82z7gg5B55jFy6lBHR32aSpdcdEZN+6jwHKbNAUsKe/h9WEflsVSfVRg++CP3Mr+NTxWEQGCDNSdk+H8N+6yTYqJma2wuSr+UHupcGWJZPDXsbzquElVm417OFCIQ3TIEanNNn8yDRjf1cLb6dbF3/kjxPA23XsGMwb6zxWhyzU9TWKx/dCv8m0EacHUtJk9+B3FmGFDB+N5dsgnyoQztgswtRlL3wLb+5oyHtTLfK7+XhNw4hN24huXCqMNLMpTgp4YaxT1xEkp9OBWwYp5D2eSsnZ9/rmruf2SR3Kb/W8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Seats-of-the-Mighty-Volume-1_6224
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy